# Generated by Django 2.2 on 2019-04-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_course', models.CharField(blank=True, max_length=255, null=True)),
                ('user_primary_language', models.CharField(max_length=255)),
                ('user_secondary_language', models.CharField(blank=True, max_length=255, null=True)),
                ('user_preferred_time', models.IntegerField()),
                ('user_preferred_day', models.IntegerField()),
                ('user_preferred_location', models.CharField(max_length=255)),
            ],
        ),
    ]
