# Generated by Django 2.2 on 2019-04-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190418_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_preferred_day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_preferred_time',
            field=models.PositiveIntegerField(),
        ),
    ]
