# Generated by Django 2.2 on 2019-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190419_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_preferred_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_preferred_time',
            field=models.IntegerField(),
        ),
    ]
