# Generated by Django 2.1.7 on 2019-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='location',
            new_name='meeting_location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lanuage',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_course',
            field=models.CharField(default='CRN', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Group Name', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_primary_lanuage',
            field=models.CharField(default='English', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_secondary_lanuage',
            field=models.CharField(default='N/A', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_day',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='owner_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_time',
            field=models.IntegerField(),
        ),
    ]
