# Generated by Django 2.2 on 2019-04-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190418_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
