# Generated by Django 2.2 on 2019-04-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190418_2211'),
        ('groups', '0002_group_course'),
    ]

    operations = [
    ]
