# Generated by Django 2.2 on 2019-04-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_course'),
        ('groups', '0004_delete_user'),
    ]

    operations = [
    ]
