# Generated by Django 2.2 on 2019-04-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_merge_20190419_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='meeting_day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_time',
            field=models.PositiveIntegerField(),
        ),
    ]
