# Generated by Django 2.2 on 2019-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20190419_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='meeting_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_time',
            field=models.IntegerField(),
        ),
    ]
